# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: y:/EMBD_Projects/ip_repo/BubbleSortIP/BubbleSortIP_1.0/src/fifo_generator_0/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/EMBD_Projects/ip_repo/BubbleSortIP/BubbleSortIP_1.0/src/fifo_generator_0/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: y:/EMBD_Projects/ip_repo/BubbleSortIP/BubbleSortIP_1.0/src/fifo_generator_0/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: y:/EMBD_Projects/ip_repo/BubbleSortIP/BubbleSortIP_1.0/src/fifo_generator_0/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/EMBD_Projects/ip_repo/BubbleSortIP/BubbleSortIP_1.0/src/fifo_generator_0/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: y:/EMBD_Projects/ip_repo/BubbleSortIP/BubbleSortIP_1.0/src/fifo_generator_0/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
